# Kick off a WAS scan 

steps: 
- task: QualysWASConnector@1
  displayName: Scan with WAS
  inputs:
    webApplication: '267694489-DF-TiredfulAPI'
    scanType: 'DISCOVERY'
    failBySeverity5: true
    sev5: '0'
    dataCheckFrequency: '2'
    waitTimeforScanResult: '60*24'
    WasService: 'user-quays2ng78'
