# Kick off a WAS scan 

steps: 
- task: QualysWASConnector@1
  displayName: "Qualys WAS scan"
  inputs:
    webApplication: '267694489-DF-TiredfulAPI'
    scanType: 'VULNERABILITY'
    failBySeverity4: true
    sev4: '0'
    failBySeverity5: true
    sev5: '0'
    failwithAnyQIDs: true
    qidlist: '150022'
    failIfWasCouldNotScan: true
    dataCheckFrequency: '5'
    waitTimeforScanResult: '60*24'
    WasService: 'qualys-us2-conn'
