# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: gmdavef-docker-registry-conn
  
stages:
- stage:
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
#    pool:
#      vmImage: 'ubuntu-latest'
    steps: 
    - task: QualysWASConnector@1
      displayName: Scan with WAS
      inputs:
        webApplication: '195005837-Gruyere'
        scanType: 'DISCOVERY'
        authenticationRecord: 'Use Default'
        failBySeverity4: true
        sev4: '0'
        failBySeverity5: true
        sev5: '0'
        failIfWasCouldNotScan: true
        dataCheckFrequency: '3'
        waitTimeforScanResult: '60*24'
        WasService: 'user-quays2ng78'    
#    - task: Docker@2
#      displayName: Build and push an image to container registry
#      inputs:
#        command: buildAndPush
#        repository: test-may-1
#        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#        containerRegistry: $(dockerRegistryServiceConnection)
#        tags: |
#          $(tag)
